const pacientes = new Array({
        nombre: 'Lucia',
        apellido: 'Alvarez',
        edad: 43,
        diagnostico: 'Gripe',
        numeroSS: 'A123456'
    }, {
        nombre: 'Carlos',
        apellido: 'Andres',
        edad: 56,
        diagnostico: 'Diabetes',
        numeroSS: 'K34567000',
    }, {
        nombre: 'Pablo',
        apellido: 'Motos',
        edad: 56,
        diagnostico: 'Calvicie',
        numeroSS: 'R4867000',
    }, {
        nombre: 'Jose',
        apellido: 'Dominguez',
        edad: 67,
        diagnostico: 'Alzhaimer',
        numeroSS: 'O934571',
    }, {
        nombre: 'Elena',
        apellido: 'Prados',
        edad: 18,
        diagnostico: 'Intoxicacion',
        numeroSS: 'I823455',
    }, {
        nombre: 'Maria',
        apellido: 'Carreño',
        edad: 45,
        diagnostico: 'Cancer',
        numeroSS: 'P123454',
    }, {
        nombre: 'Pepe',
        apellido: 'Guzman',
        edad: 89,
        diagnostico: 'Depresion',
        numeroSS: 'Q12362548',
    }, {
        nombre: 'Ricardo',
        apellido: 'Gomez',
        edad: 24,
        diagnostico: 'Diabetes',
        numeroSS: 'I324610',
    }, {
        nombre: 'Sasha',
        apellido: 'Grey',
        edad: 28,
        diagnostico: 'Anorexia',
        numeroSS: 'Q345126',
    }, {
        nombre: 'Mia',
        apellido: 'Khalifa',
        edad: 27,
        diagnostico: 'Calvicie',
        numeroSS: 'Q124500',
    }, {
        nombre: 'Pepe',
        apellido: 'Gomez',
        edad: 65,
        diagnostico: 'Ulceras',
        numeroSS: 'K123652',
    }, {
        nombre: 'Pepita',
        apellido: 'Juarez',
        edad: 48,
        diagnostico: 'Gota',
        numeroSS: 'S231583',
    },

)