export const MODIFICA_PERSONAL_DATA = 'MODIFICA_PERSONAL_DATA';

export const MODIFICA_PROFESIONAL_DATA = 'MODIFICA_PROFESIONAL_DATA';
export const MODIFICA_AFICIONES_DATA = 'MODIFICA_AFICIONES_DATA';
export const MODIFICA_PORCENTAJE_DATA = 'MODIFICA_PORCENTAJE_DATA';
